### PR TITLE
Avoid failing to load property pages on missing prop page

### LINKED ISSUE #6192: When AppDesigner page crashes, our telemetry crashes trying to report usage
**Visual Studio Version**:

In https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1116108, there's a telemetry session that shows that when a page crashes, we fail to send a telemetry event, hiding the original crash from showing up in the tab.

**Summary**:

```
P | reserved.channelused |   | aivortex
-- | -- | -- | --
P | reserved.datamodel.correlationid |   | 59c96c8c-6586-4b11-91d7-c4dcee4d11e3
P | reserved.datamodel.entityname |   | application-designer-window-pane-fault
P | reserved.datamodel.entitytype |   | Fault
P | reserved.datamodel.fault.addederrorinformation |   | False
P | reserved.datamodel.fault.exception.message |   | Value cannot be null. Parameter name: val
P | reserved.datamodel.fault.exception.paramname |   | val
P | reserved.datamodel.fault.exception.stacktrace |   | ["Microsoft.VisualStudio.Telemetry.TelemetryPiiProperty..ctor(Object)","Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerView.AddTabs(PropertyPageInfo[])","Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerView.InitView()","Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerWindowPane.PopulateView()"]
P | reserved.datamodel.fault.exception.typestring |   | System.ArgumentNullException
P | reserved.datamodel.fault.faultseverity |   | Uncategorized
P | reserved.datamodel.fault.issampled |   | True
P | reserved.datamodel.fault.watsonnotsentreason |   | NoExtraDataAdded
P | reserved.datamodel.featurename |   | ml/proppages/appdesigner
P | reserved.datamodel.productname |   | vs
P | reserved.datamodel.source |   | DataModelApi

```

it appears we're crashing on attempting to create a property representing the caption.

### PR DESCRIPTION
**Pull request by davkean**
When encountering a property page that cannot be found, we'd skip it from the list of pages. https://github.com/dotnet/project-system/pull/5575 regressed  this however, by throwing an an ArgumentNullException while trying to report telemetry for the tab title. Skip that in that case.

Fixes: https://github.com/dotnet/project-system/issues/6192

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/project-system/pull/6653)

### CODE REVIEW

**Review by swesonga — APPROVED** [review]
:shipit:

File: src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb [hunk 1]
```diff
@@ -720,15 +720,18 @@ Namespace Microsoft.VisualStudio.Editors.ApplicationDesigner
...
+                            SpecialTabsTelemetryEvent.Properties(TelemetryPropertyPrefix + "TabInfo.TabTitle") = New TelemetryPiiProperty(.EditorCaption)
+                            SpecialTabsTelemetryEvent.Properties(TelemetryPropertyPrefix + "TabInfo.GUID") = PropertyPages(Index).Guid.ToString("B")
+                            SpecialTabsTelemetryEvent.Properties(TelemetryPropertyPrefix + "Project.Extension") = IO.Path.GetExtension(_projectFilePath)
+                            SpecialTabsTelemetryEvent.Properties(TelemetryPropertyPrefix + "Project.GUID") = _projectGuid.ToString("B")
+                            TelemetryService.DefaultSession.PostEvent(SpecialTabsTelemetryEvent)
+                        End If
 
                     Else
-                        Dim FileName As String = DirectCast(AppDesignerItems(Index - PropertyPages.Length), String)
+                            Dim FileName As String = DirectCast(AppDesignerItems(Index - PropertyPages.Length), String)
```
Comment (drewnoakes) [inline src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb:734]: Intentional?

**Review by drewnoakes — APPROVED** [review]
